# Generated by Django 4.0.4 on 2022-06-08 06:23

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.user_directory_path)),
                ('ttf_file', models.URLField(blank=True, null=True)),
                ('woff_file', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Accept', 'Accept'), ('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Canceled', max_length=10)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
