# Generated by Django 4.0.4 on 2022-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='ttf_file',
            field=models.FilePathField(path='/home/dice/HandWriteFont_BE/handwritefont_be/media', recursive=True),
        ),
        migrations.AlterField(
            model_name='font',
            name='woff_file',
            field=models.FilePathField(path='/home/dice/HandWriteFont_BE/handwritefont_be/media', recursive=True),
        ),
    ]
