trainer:
  work_dir: ./result/evaluator
  max_epoch: 90

dset:
  train:
    data_dir: data_example/kor/jpg
    chars: data/kor/eval_chars.json
    extension: jpg
    save_list: True
  val:
    n_val_example: 128
    data_dir: data_example/kor/jpg
    extension: jpg